[package]
name = "TelemetryReader"
version = "0.1.0"
edition = "2021"
authors = ["vlasel <vladyslav.selishchev@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "telemetry_reader"
path = "src/main.rs"